#!/bin/zsh

alias ls='ls -Gh'
alias ll='ls -l'
alias la='ls -lA'
alias l='la'
alias grep='grep --color'
alias Preview='/Applications/Preview.app/Contents/MacOS/Preview'
alias wget='curl -O'

# emacs
alias e='openemacs '

# VIM
alias gvimp='gvim -p'
alias mvimdiff='mvim -d'
alias v='mvim --remote-tab-silent'
alias d='mvimdiff'

# Apache / mysql
alias amstart='sudo /opt/local/apache2/bin/apachectl start; sudo /opt/local/bin/mysqld_safe5 &'
alias apache2ctl='sudo /opt/local/apache2/bin/apachectl'
alias mysqlstart='sudo mysqld_safe5 &'
alias mysqlstop='mysqladmin5 -u root shutdown'
alias mysql='mysql5'

# rails
alias rss='script/server'
alias rsg='script/generate'

# hamachi
alias hamachi='sudo hamachi'

# git
alias ga='git add'
alias ga.='ga .'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit -a'
alias gco='git checkout'
alias gd='git diff'
alias gf='git fetch'
alias gl='git pull'
alias glo='git log'
alias glog='git log'
alias gm='git merge'
alias gp='git push'
alias gs='git status'
alias gsm='git submodule init'
alias gsv='git svn'

# subversion
alias setSvnExternals='svn propset svn:externals -F ./EXTERNALS.TXT .'
alias setSvnIgnore='svn propset svn:ignore -F ./IGNORE.TXT .'
alias ss="svn st | grep -v '^Performing' | grep -v '^$'"
alias ssm="svn st | grep -v '^Performing' | grep -v '^$' | grep -v '^X'"

rationalise-dot() {
if [[ $LBUFFER = *.. ]]; then
    LBUFFER+=/..
else
    LBUFFER+=.
fi
}
zle -N rationalise-dot
bindkey . rationalise-dot

alias ..='cd ..'
alias ...='cd ../..'


# Mac Application aliases
alias firefox='open -a firefox'
alias preview='open -a Preview'
alias camino='open -a Camino'
alias mail='open -a Mail'
alias skype='open -a Skype'
alias adium='open -a Adium'
alias ical='open -a ICal'
alias finder='open -a Finder'
alias notes='open -a Stickies'
alias tasks='open -a TaskCoach'
alias emacs='open -a Emacs'
alias taskcoach='open -a TaskCoach'
alias seleniumrc='/Users/jone/Apps/selenium-server-1.0.1/start_selenium_rc.sh'

# python stuff
alias manager='bin/manager/manager.py'
alias eggdist='python2.4 setup.py mregister sdist bdist_egg mupload -r '

#Extensions
alias -s pdf=preview
alias -s odt=preview
alias -s doc=preview
alias -s docx=preview
alias -s rtf=preview
alias -s ods=preview
alias -s xls=preview
alias -s xlsx=preview
alias -s odp=preview
alias -s ppt=preview
alias -s pptx=preview

alias -s htm=firefox
alias -s html=firefox
alias -s xml=firefox

alias -s png=preview
alias -s jpg=preview
alias -s gif=preview

alias -s php=php
alias -s py=python

alias -s el=emacs
alias -s tsk=taskcoach

# phone remote control
alias phone_accept='curl "http://192.168.1.66/adr.htm?number=33"'
